s10day12bbs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from bbs import views
from webqq import urls as webqq_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index),
    url(r'^life/$', views.life, name='life'),
    url(r'^tech/$', views.tech, name='tech'),
    url(r'^1024/$', views.category1024, name='category1024'),
    url(r'^login/$', views.account_login, name='login'),
    url(r'^article/(\d+)/$', views.article, name='article'),
    url(r'^article/edit/$', views.edit_article, name='edit_article'),
    url(r'^chat/', include(webqq_urls))
]

webqq/urls.py
#!/usr/bin/env python
# Name: urls.py
# Time:8/4/16 3:01 PM
# Author:luo1fly

from django.conf.urls import include, url
from webqq import views

urlpatterns = [
    url(r'^$', views.dashboard, name='chatroom'),
    url(r'^send_msg/$', views.send_msg, name='chat_send_msg'),
    url(r'^get_msg/$', views.get_msg, name='get_new_msg'),
]

bbs/models.py
from django.db import models
from django.contrib.auth.models import User
from s10day12bbs import settings

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=256)
    category = models.ForeignKey('Category')    # 一对多关系，单选
    content = models.TextField()
    summary = models.CharField(max_length=256)
    author = models.ForeignKey('UserProfile')   # 一对多关系，单选
    head_img = models.ImageField(upload_to=settings.default_img_path)   # imgs/upload/
    '''
    upload_to参数用于设定admin后台图片上传路径，如直接给定真实路径statics/*则会与前端展示url地址static/*冲突，
    为避免该麻烦，数据库中不写死二级目录，而是写到三级目录imgs/*，前端展示时拼接static/，
    后台的修改采用软连接方式ln -s statics/imgs imgs
    '''
    create_on = models.DateTimeField(auto_now_add=1)

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=32, unique=1)
    admins = models.ManyToManyField('UserProfile')  # 多对多关系，一个版块可以有多个管理员，多选

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=32)
    user_groups = models.ManyToManyField('UserGroup')   # 多对多关系，一个用户可以属于多个组，多选
    friends = models.ManyToManyField('self', blank=1, related_name='fid')

    def __str__(self):
        return self.name


class UserGroup(models.Model):
    name = models.CharField(max_length=32, unique=1)

    def __str__(self):
        return self.name


class ThumbUp(models.Model):
    article = models.ForeignKey('Article')  # 一对多关系，单选，一个点赞只能针对一条博客
    user = models.ForeignKey('UserProfile')     # 一对多关系，单选，一个点赞只能有一个执行者
    add_date = models.DateTimeField(auto_now_add=1)

    def __str__(self):
        return self.article.title


class Comment(models.Model):
    article = models.ForeignKey('Article')
    comment = models.TextField(max_length=1024)
    user = models.ForeignKey('UserProfile')
    parent_comment = models.ForeignKey('self', blank=1, null=1, related_name='pid')
    # 关联到自己，单选，一条评论只能有一条父评论，但一条父评论可以有多个子评论，另外在做自关联的时候要加related_name参数
    add_date = models.DateTimeField(auto_now_add=1)

    def __str__(self):
        return self.comment

hosts/models.py
from django.db import models

# Create your models here.

webqq/models.py
from django.db import models
from bbs.models import UserProfile
# Create your models here.


class QQGroup(models.Model):
    name = models.CharField(max_length=64)
    founder = models.ForeignKey(UserProfile)
    admins = models.ManyToManyField(UserProfile, related_name='admins')
    members = models.ManyToManyField(UserProfile, related_name='members')
    mem_limits = models.IntegerField(default=200)
    descriptions = models.TextField(max_length=256)

    def __str__(self):
        return self.name

bbs/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from bbs import models
from bbs import utils
from django.http import Http404
from django.core.exceptions import ObjectDoesNotExist
import json
from django.contrib.auth import authenticate, login

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.


def account_login(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    else:
        # print(request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            user.userprofile.online = True
            user.userprofile.save()
            return HttpResponseRedirect("/")
        else:
            login_err = 'Wrong username or password!'
            return render(request, 'login.html', locals())


def index(request):
    articles = models.Article.objects.all().order_by('-create_on')
    paginator = Paginator(articles, 4)  # Show 4 contacts per page

    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        articles = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        articles = paginator.page(paginator.num_pages)
    # print(articles)
    return render(request, 'index.html', locals())


def life(request):
    return render(request, 'life.html')


def tech(request):
    return render(request, 'tech.html')


def category1024(request):
    return render(request, '1024.html')


def article(request, article_id):
    error_msg = ''

    try:
        art = models.Article.objects.get(id=article_id)
    except ObjectDoesNotExist as e:
        error_msg = e.args[0]
    else:
        comments = utils.ArticleHandler.build_comments_tree(art)
        # print(locals())
        return render(request, 'article.html', locals())


def edit_article(request):
    if request.method == 'GET':
        return render(request, 'article_edit.html', locals())
    elif request.method == 'POST':
        # print(request.POST)
        art_handler = utils.ArticleHandler(request)
        res = art_handler.create()
        return HttpResponse('hi....')

hosts/views.py
from django.shortcuts import render

# Create your views here.

webqq/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
import json
import datetime
from webqq import utils
from bbs import models


# Create your views here.

global_msg_dic = {}


def dashboard(request):
    return render(request, 'webqq/dashboard.html', locals())


def send_msg(request):
    # print(request.POST)
    data = request.POST['data']
    data = json.loads(data)
    print(data)
    from_id = data['from_id']
    to_id = data['to_id']
    contact_type = data['contact_type']
    data['date'] = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    if contact_type == 'single':
        if to_id not in global_msg_dic:
            global_msg_dic[to_id] = utils.Chat()
        global_msg_dic[to_id].put_msg(data)
        print("push msg [%s] to user:%s's que" % (data['msg'],
                                                  models.UserProfile.objects.get(id=to_id),
                                                  ))
    # print(global_msg_dic)
    return HttpResponse('success')


def get_msg(request):
    # print(request.GET)
    # print('global_msg_dic:', global_msg_dic)
    uid = request.GET['user_id']
    # print('uid:', uid)
    if uid:
        res = None
        if uid in global_msg_dic:
            res = global_msg_dic[uid].get_msg()
        return HttpResponse(json.dumps(res))
    return HttpResponse(json.dumps('chucuole'))

templates/1024.html
{% extends 'index.html' %}


{% block content-left %}

    1024

{% endblock %}

{% block content-right %}
    right bar
{% endblock %}

templates/article.html
{% extends 'index.html' %}
{% load custom %}

{% block content-left %}
    <div class="blog-head">
        <h3>{{ art.title }} </h3>
        <div class="head-img">
            <img  src="/static/{{ art.head_img }}" >
        </div>
        <div class="blog-summary-btn">
            <a>{{ art.author.name }} |   </a>
            <span>{{ art.publish_date }}</span>
            <span><i class="fa fa-comment-o"></i>{{ art.comment_set.select_related.count }}</span>
            <span><i class="fa fa-star"></i>{{ art.thumbup_set.selelct_related.count }}</span>
        </div>

        <div class="blog-content">
            {{ art.content|safe }}
        </div>

        <div class="comments-box">
        {% build_comment_tree comments as ac %}
            {{ ac|safe }}
        </div>

    </div>


{% endblock %}

{% block content-right %}
    right bar
{% endblock %}

templates/article_edit.html
{% extends 'index.html' %}

{% block container%}
    <form class="form-horizontal" method="post" action="{% url "edit_article" %}"
          enctype="multipart/form-data">{% csrf_token %}{# enctype 用于允许上传多媒体文件 #}
      <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">文章标题</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" name="title" placeholder="title...">
        </div>
      </div>
      <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">文章简介</label>
        <div class="col-sm-10">
            <textarea class="form-control" rows="3" name="summary"></textarea>
        </div>
      </div>
      <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">标题图片</label>
        <div class="col-sm-10">
            <input type="file" name="head_img" />
        </div>{# 上传文件输入框 #}
      </div>
      <div class="form-group">
        <label for="inputPassword3" class="col-sm-2 control-label">内容</label>
        <div class="col-sm-10">
          <textarea id="create_bbs" name="content"></textarea>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">发贴</button>
        </div>
      </div>
    </form>
{% endblock %}

{% block bottom-js %}
<script  src="/static/plugins/tinymce/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
tinymce.init({
            selector: "#create_bbs",
            theme: "modern",
            //width: 300,
            height: 300,
            plugins: [
                 "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
                 "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                 "save table contextmenu directionality emoticons template paste textcolor"
           ],
           //content_css: "css/content.css",
           toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor emoticons",
           style_formats: [
                {title: 'Bold text', inline: 'b'},
                {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
                {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
                {title: 'Example 1', inline: 'span', classes: 'example1'},
                {title: 'Example 2', inline: 'span', classes: 'example2'},
                {title: 'Table styles'},
                {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
            ]
        });
</script>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Post - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css">
    <!-- Custom CSS -->
    <link href="/static/css/blog-post.css" rel="stylesheet">
    <link href="/static/css/custom2.css" rel="stylesheet">
    <link href="/static/css/bootstrap.vertical-tabs.css" rel="stylesheet">



    {% block head-css %}
    {% endblock %}

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">XOXO</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul id="top_menu" class="nav navbar-nav">
                    <li>
                        <a href="/">全部</a>
                    </li>
                    <li>
                        <a href="{% url 'life' %}">生活</a>
                    </li>
                    <li>
                        <a href="{% url 'tech' %}">技术</a>
                    </li>
                    <li>
                        <a href="{% url 'category1024' %}">1024</a>
                    </li>
                    <li>
                        <a href="{% url 'chatroom' %}">聊天室</a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="#">{{ request.user.userprofile.name }} </a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'login' %}">登录/注册</a>
                    </li>
                    {% endif %}

                </ul>

            </div>
            <!-- /.navbar-collapse -->

        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    {% block page-container %}
    <div class="container">
        {% block container %}
        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">
                {% block content-left %}
                <!-- Blog Post -->
                <div class="hide new_bbs_reminder">
                <span> </span>条新消息入榜,点击查看
                </div>

                {% for article in articles %}

                <div class="blog-box row">
                    <div class="head-img col-md-4">
                        <img  src="/static/{{ article.head_img }}" >
                    </div>
                    <div class="blog-summary-box col-md-8">
                        <h3><a href="{% url 'article' article.id %}">
                                {{ article.title }}
                            </a></h3>
                        <div class="blog-summary-btn">
                            <a>{{ article.author.name }}</a>
                            <span>{{ article.create_on }}</span>

                             <span><i class="fa fa-star"></i>4</span>
                             <span><i class="fa fa-comment-o"></i>9</span>
                             <span><i class="fa fa-wechat"></i>10</span>
                        </div>
                        <div class="blog-summary">
                            {{ article.summary }}
                        </div>
                    </div>
                 </div>
                    <hr/>
                {% endfor %}

                <div class="pagination">
                    <nav>
                        <ul class="pagination">
                            {% if articles.has_previous %}
                                <li><a href="?page={{ articles.previous_page_number }}">上一页</a></li>
                            {% endif %}

                            {% for p_num in articles.paginator.page_range  %}
                                {% if p_num == articles.number %}
                                     <li class="active"><a href="?page={{ p_num }}">{{ p_num }}</a></li>
                                {% else %}
                                     <li ><a href="?page={{ p_num }}">{{ p_num }}</a></li>
                                {% endif %}
                            {% endfor %}

                            {% if articles.has_next %}
                                <li ><a href="?page={{ articles.next_page_number }}" >下一页</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>




                {% endblock %}
            </div>


            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">
                {% block content-right %}
                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>
                {% endblock %}
            </div>

        </div>
        <!-- /.row -->

        <hr>
        {% endblock %}
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    {% endblock %}
    <!-- /.container -->

    <!-- jQuery -->
    <script src="/static/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/js/bootstrap.min.js"></script>
    {% block bottom-js %}
    <script type="text/javascript">


    </script>

    {% endblock %}
<script type="text/javascript">

    $(document).ready(function(){

        $("#top_menu a").each(function(){

            if ($(this).attr("href") == "{{ request.path }}"){
                $(this).parent().addClass("active");
            };
        });//end each

        /*

        */






    });// end doc ready

</script>

</body>

</html>

templates/life.html
{% extends 'index.html' %}


{% block content-left %}

    生活页

{% endblock %}

{% block content-right %}
    right bar
{% endblock %}

templates/login.html
{% extends 'index.html' %}

{% block container %}
<div>
    <form method="post" action="{% url 'login' %}">{% csrf_token %}

        <input type="text" name="username" placeholder="username" />
        <input type="password" name="password" placeholder="password" />
        <input type="submit" value="Login" class="btn btn-success" />

    </form>

    <p style="color: red">{{ login_err }}</p>
</div>

{% endblock %}

templates/tech.html
{% extends 'index.html' %}


{% block content-left %}

    technique

{% endblock %}

{% block content-right %}
    right bar
{% endblock %}

templates/webqq/dashboard.html
{% extends 'index.html' %}


{% block container %}

    {% csrf_token %}
<div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#contact-box" aria-controls="home" role="tab" data-toggle="tab">联系人</a></li>
    <li role="presentation"><a href="#contact-group-box" aria-controls="profile" role="tab" data-toggle="tab">群组</a></li>
    <li role="presentation"><a href="#Config" aria-controls="messages" role="tab" data-toggle="tab">选项</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">

    <div role="tabpanel" class="tab-pane active" id="contact-box">
        <div class="row chat-box">
            <div class="contact-list col-md-3">
                <div class="contact-list-content">
                    <form class="navbar-form" method="get" action="/">
                        <input type="text" class="form-control" name="s" id="s" style="width: 200px;">
                        <button type="submit" class="btn btn-default">搜索</button>
                    </form>
                    <div id="list-group">
                            {% for contact in request.user.userprofile.friends.select_related %}
                                <a contact-id="{{ contact.id }}" contact-type="single" href="#" class="list-group-item" >
                                    {{ contact.name }}
                                </a>
                            {% endfor %}
                    </div>
                </div>
            </div>
            <div class="dialog-box col-md-9">
                <div class="dialog-box-header">

                </div>
                <div class="dialog-box-content">

                </div>
                <div class="dialog-box-utils">
                    chat-box-utils
                </div>
                <div class="dialog-box-msg">
                    <textarea name="msg"></textarea>
                </div>
            </div>
        </div>
    </div>

    <div role="tabpanel" class="tab-pane" id="contact-group-box">群组</div>
    <div role="tabpanel" class="tab-pane" id="Config">选项</div>
  </div>

</div>

{% endblock %}

{% block bottom-js %}
    <script type="text/javascript">
        $(document).ready(function () {
            RefreshMsgs = setInterval(function () {
                GetNewMsg();
            },3000);

            $("#list-group a").click(function () {
                $(this).addClass("active");
                $(this).siblings().removeClass("active");

                SwitchChatBox(this);
            });

            $("body").delegate('textarea', 'keydown', function (e) {
                if (e.which == 13) {
                    var msg_txt = $('textarea').val();
                    if ($.trim(msg_txt).length > 0) {
                        console.log(msg_txt);
                        SendMsg(msg_txt);
                    };
                    AddSendMsgIntoBox(msg_txt);
                    $('textarea').val('');
                }
            })
        });

        function SwitchChatBox(ele) {
            var current_uid = $(ele).attr("contact-id");
            var current_contact_type = $(ele).attr('contact-type');
            var current_contact_name = $(ele).text();
            var dialog_head_html = '<span contact-id="'+current_uid+'" contact-type="'+current_contact_type+'">'+current_contact_name+'</span>';

            $(".dialog-box-header").html(dialog_head_html)
        };

        function SendMsg(msg) {
            var msg_dic = {
                'from_id': {{ request.user.userprofile.id }},
                'to_id': $(".dialog-box-header span").attr("contact-id"),
                'contact_type': $(".dialog-box-header span").attr("contact-type"),
                'msg': msg,
            }
            $.post("{% url 'chat_send_msg' %}", {'data': JSON.stringify(msg_dic), 'csrfmiddlewaretoken': $("input[name='csrfmiddlewaretoken']").attr('value')}, function(callback){
                console.log(callback);
            });
        };

        function GetNewMsg() {
            var current_contact_id = $(".dialog-box-header span").attr('contact-id')
            $.get("{% url 'get_new_msg' %}",
                    {'user_id':{{ request.user.userprofile.id }} },
                    function(callback){
                        callback = JSON.parse(callback);
                        console.log(callback)
                        AddSendMsgIntoBox(callback);
{#                        $(".dialog-box-content").html(callback)#}

                    });
        };

        function AddSendMsgIntoBox(msg_txt) {
            var msg_div = "<div class='pull right'>" +
                            "<span>" + {{ request.user.userprofile.name }} + "</span>" +
                            "<br>" +
                            "<span>" + new Date().toLocaleDateString() + "</span>" +
                            "<p>" + msg_txt + "</p>" +
                            "</div>";
            $(".dialog-box-content").append(msg_div);
            $(".dialog-box-content").animate({
                scrollTop: $(".dialog-box-content")[0].scrollHeight
            },500);
        };
    </script>
{% endblock %}